//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1434.
// 
#pragma warning disable 1591

namespace Esra.Web.CatOps {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CatbertWebServiceSoap", Namespace="CAESDO.Services")]
    public partial class CatbertWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SecurityContext securityContextValueField;
        
        private System.Threading.SendOrPostCallback SearchNewUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertNewUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback AssignPermissionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletePermissionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddUnitOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUnitOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUnitsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUnitsByUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRolesByUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersByApplicationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersByApplicationRoleOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddPhoneNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmailTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPhoneTypesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CatbertWebService() {
            this.Url = global::Esra.Web.Properties.Settings.Default.Esra_Web_CatOps_CatbertWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SecurityContext SecurityContextValue {
            get {
                return this.securityContextValueField;
            }
            set {
                this.securityContextValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SearchNewUserCompletedEventHandler SearchNewUserCompleted;
        
        /// <remarks/>
        public event InsertNewUserCompletedEventHandler InsertNewUserCompleted;
        
        /// <remarks/>
        public event VerifyUserCompletedEventHandler VerifyUserCompleted;
        
        /// <remarks/>
        public event AssignPermissionsCompletedEventHandler AssignPermissionsCompleted;
        
        /// <remarks/>
        public event DeletePermissionsCompletedEventHandler DeletePermissionsCompleted;
        
        /// <remarks/>
        public event AddUnitCompletedEventHandler AddUnitCompleted;
        
        /// <remarks/>
        public event DeleteUnitCompletedEventHandler DeleteUnitCompleted;
        
        /// <remarks/>
        public event GetUnitsCompletedEventHandler GetUnitsCompleted;
        
        /// <remarks/>
        public event GetUnitsByUserCompletedEventHandler GetUnitsByUserCompleted;
        
        /// <remarks/>
        public event GetRolesCompletedEventHandler GetRolesCompleted;
        
        /// <remarks/>
        public event GetRolesByUserCompletedEventHandler GetRolesByUserCompleted;
        
        /// <remarks/>
        public event GetUsersByApplicationsCompletedEventHandler GetUsersByApplicationsCompleted;
        
        /// <remarks/>
        public event GetUsersByApplicationRoleCompletedEventHandler GetUsersByApplicationRoleCompleted;
        
        /// <remarks/>
        public event AddEmailCompletedEventHandler AddEmailCompleted;
        
        /// <remarks/>
        public event AddPhoneNumberCompletedEventHandler AddPhoneNumberCompleted;
        
        /// <remarks/>
        public event GetEmailTypesCompletedEventHandler GetEmailTypesCompleted;
        
        /// <remarks/>
        public event GetPhoneTypesCompletedEventHandler GetPhoneTypesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CAESDO.Services/SearchNewUser", RequestNamespace="CAESDO.Services", ResponseNamespace="CAESDO.Services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Users[] SearchNewUser(string eid, string firstName, string lastName, string login) {
            object[] results = this.Invoke("SearchNewUser", new object[] {
                        eid,
                        firstName,
                        lastName,
                        login});
            return ((Users[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchNewUserAsync(string eid, string firstName, string lastName, string login) {
            this.SearchNewUserAsync(eid, firstName, lastName, login, null);
        }
        
        /// <remarks/>
        public void SearchNewUserAsync(string eid, string firstName, string lastName, string login, object userState) {
            if ((this.SearchNewUserOperationCompleted == null)) {
                this.SearchNewUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchNewUserOperationCompleted);
            }
            this.InvokeAsync("SearchNewUser", new object[] {
                        eid,
                        firstName,
                        lastName,
                        login}, this.SearchNewUserOperationCompleted, userState);
        }
        
        private void OnSearchNewUserOperationCompleted(object arg) {
            if ((this.SearchNewUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchNewUserCompleted(this, new SearchNewUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CAESDO.Services/InsertNewUser", RequestNamespace="CAESDO.Services", ResponseNamespace="CAESDO.Services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertNewUser(Users user) {
            object[] results = this.Invoke("InsertNewUser", new object[] {
                        user});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertNewUserAsync(Users user) {
            this.InsertNewUserAsync(user, null);
        }
        
        /// <remarks/>
        public void InsertNewUserAsync(Users user, object userState) {
            if ((this.InsertNewUserOperationCompleted == null)) {
                this.InsertNewUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertNewUserOperationCompleted);
            }
            this.InvokeAsync("InsertNewUser", new object[] {
                        user}, this.InsertNewUserOperationCompleted, userState);
        }
        
        private void OnInsertNewUserOperationCompleted(object arg) {
            if ((this.InsertNewUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertNewUserCompleted(this, new InsertNewUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CAESDO.Services/VerifyUser", RequestNamespace="CAESDO.Services", ResponseNamespace="CAESDO.Services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerifyUser(string loginID) {
            object[] results = this.Invoke("VerifyUser", new object[] {
                        loginID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyUserAsync(string loginID) {
            this.VerifyUserAsync(loginID, null);
        }
        
        /// <remarks/>
        public void VerifyUserAsync(string loginID, object userState) {
            if ((this.VerifyUserOperationCompleted == null)) {
                this.VerifyUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyUserOperationCompleted);
            }
            this.InvokeAsync("VerifyUser", new object[] {
                        loginID}, this.VerifyUserOperationCompleted, userState);
        }
        
        private void OnVerifyUserOperationCompleted(object arg) {
            if ((this.VerifyUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyUserCompleted(this, new VerifyUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CAESDO.Services/AssignPermissions", RequestNamespace="CAESDO.Services", ResponseNamespace="CAESDO.Services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AssignPermissions(string login, string application, int role) {
            object[] results = this.Invoke("AssignPermissions", new object[] {
                        login,
                        application,
                        role});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AssignPermissionsAsync(string login, string application, int role) {
            this.AssignPermissionsAsync(login, application, role, null);
        }
        
        /// <remarks/>
        public void AssignPermissionsAsync(string login, string application, int role, object userState) {
            if ((this.AssignPermissionsOperationCompleted == null)) {
                this.AssignPermissionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAssignPermissionsOperationCompleted);
            }
            this.InvokeAsync("AssignPermissions", new object[] {
                        login,
                        application,
                        role}, this.AssignPermissionsOperationCompleted, userState);
        }
        
        private void OnAssignPermissionsOperationCompleted(object arg) {
            if ((this.AssignPermissionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AssignPermissionsCompleted(this, new AssignPermissionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CAESDO.Services/DeletePermissions", RequestNamespace="CAESDO.Services", ResponseNamespace="CAESDO.Services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeletePermissions(string login, string application, int role) {
            object[] results = this.Invoke("DeletePermissions", new object[] {
                        login,
                        application,
                        role});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeletePermissionsAsync(string login, string application, int role) {
            this.DeletePermissionsAsync(login, application, role, null);
        }
        
        /// <remarks/>
        public void DeletePermissionsAsync(string login, string application, int role, object userState) {
            if ((this.DeletePermissionsOperationCompleted == null)) {
                this.DeletePermissionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletePermissionsOperationCompleted);
            }
            this.InvokeAsync("DeletePermissions", new object[] {
                        login,
                        application,
                        role}, this.DeletePermissionsOperationCompleted, userState);
        }
        
        private void OnDeletePermissionsOperationCompleted(object arg) {
            if ((this.DeletePermissionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletePermissionsCompleted(this, new DeletePermissionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CAESDO.Services/AddUnit", RequestNamespace="CAESDO.Services", ResponseNamespace="CAESDO.Services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddUnit(string login, int unitID) {
            object[] results = this.Invoke("AddUnit", new object[] {
                        login,
                        unitID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddUnitAsync(string login, int unitID) {
            this.AddUnitAsync(login, unitID, null);
        }
        
        /// <remarks/>
        public void AddUnitAsync(string login, int unitID, object userState) {
            if ((this.AddUnitOperationCompleted == null)) {
                this.AddUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUnitOperationCompleted);
            }
            this.InvokeAsync("AddUnit", new object[] {
                        login,
                        unitID}, this.AddUnitOperationCompleted, userState);
        }
        
        private void OnAddUnitOperationCompleted(object arg) {
            if ((this.AddUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddUnitCompleted(this, new AddUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CAESDO.Services/DeleteUnit", RequestNamespace="CAESDO.Services", ResponseNamespace="CAESDO.Services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteUnit(string login, int unitID) {
            object[] results = this.Invoke("DeleteUnit", new object[] {
                        login,
                        unitID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteUnitAsync(string login, int unitID) {
            this.DeleteUnitAsync(login, unitID, null);
        }
        
        /// <remarks/>
        public void DeleteUnitAsync(string login, int unitID, object userState) {
            if ((this.DeleteUnitOperationCompleted == null)) {
                this.DeleteUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUnitOperationCompleted);
            }
            this.InvokeAsync("DeleteUnit", new object[] {
                        login,
                        unitID}, this.DeleteUnitOperationCompleted, userState);
        }
        
        private void OnDeleteUnitOperationCompleted(object arg) {
            if ((this.DeleteUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUnitCompleted(this, new DeleteUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CAESDO.Services/GetUnits", RequestNamespace="CAESDO.Services", ResponseNamespace="CAESDO.Services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Units[] GetUnits() {
            object[] results = this.Invoke("GetUnits", new object[0]);
            return ((Units[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUnitsAsync() {
            this.GetUnitsAsync(null);
        }
        
        /// <remarks/>
        public void GetUnitsAsync(object userState) {
            if ((this.GetUnitsOperationCompleted == null)) {
                this.GetUnitsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUnitsOperationCompleted);
            }
            this.InvokeAsync("GetUnits", new object[0], this.GetUnitsOperationCompleted, userState);
        }
        
        private void OnGetUnitsOperationCompleted(object arg) {
            if ((this.GetUnitsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUnitsCompleted(this, new GetUnitsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CAESDO.Services/GetUnitsByUser", RequestNamespace="CAESDO.Services", ResponseNamespace="CAESDO.Services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Units[] GetUnitsByUser(string loginID) {
            object[] results = this.Invoke("GetUnitsByUser", new object[] {
                        loginID});
            return ((Units[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUnitsByUserAsync(string loginID) {
            this.GetUnitsByUserAsync(loginID, null);
        }
        
        /// <remarks/>
        public void GetUnitsByUserAsync(string loginID, object userState) {
            if ((this.GetUnitsByUserOperationCompleted == null)) {
                this.GetUnitsByUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUnitsByUserOperationCompleted);
            }
            this.InvokeAsync("GetUnitsByUser", new object[] {
                        loginID}, this.GetUnitsByUserOperationCompleted, userState);
        }
        
        private void OnGetUnitsByUserOperationCompleted(object arg) {
            if ((this.GetUnitsByUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUnitsByUserCompleted(this, new GetUnitsByUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CAESDO.Services/GetRoles", RequestNamespace="CAESDO.Services", ResponseNamespace="CAESDO.Services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Roles[] GetRoles(string application) {
            object[] results = this.Invoke("GetRoles", new object[] {
                        application});
            return ((Roles[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRolesAsync(string application) {
            this.GetRolesAsync(application, null);
        }
        
        /// <remarks/>
        public void GetRolesAsync(string application, object userState) {
            if ((this.GetRolesOperationCompleted == null)) {
                this.GetRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRolesOperationCompleted);
            }
            this.InvokeAsync("GetRoles", new object[] {
                        application}, this.GetRolesOperationCompleted, userState);
        }
        
        private void OnGetRolesOperationCompleted(object arg) {
            if ((this.GetRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRolesCompleted(this, new GetRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CAESDO.Services/GetRolesByUser", RequestNamespace="CAESDO.Services", ResponseNamespace="CAESDO.Services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Roles[] GetRolesByUser(string application, string login) {
            object[] results = this.Invoke("GetRolesByUser", new object[] {
                        application,
                        login});
            return ((Roles[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRolesByUserAsync(string application, string login) {
            this.GetRolesByUserAsync(application, login, null);
        }
        
        /// <remarks/>
        public void GetRolesByUserAsync(string application, string login, object userState) {
            if ((this.GetRolesByUserOperationCompleted == null)) {
                this.GetRolesByUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRolesByUserOperationCompleted);
            }
            this.InvokeAsync("GetRolesByUser", new object[] {
                        application,
                        login}, this.GetRolesByUserOperationCompleted, userState);
        }
        
        private void OnGetRolesByUserOperationCompleted(object arg) {
            if ((this.GetRolesByUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRolesByUserCompleted(this, new GetRolesByUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CAESDO.Services/GetUsersByApplications", RequestNamespace="CAESDO.Services", ResponseNamespace="CAESDO.Services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CatbertUsers[] GetUsersByApplications(string application) {
            object[] results = this.Invoke("GetUsersByApplications", new object[] {
                        application});
            return ((CatbertUsers[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersByApplicationsAsync(string application) {
            this.GetUsersByApplicationsAsync(application, null);
        }
        
        /// <remarks/>
        public void GetUsersByApplicationsAsync(string application, object userState) {
            if ((this.GetUsersByApplicationsOperationCompleted == null)) {
                this.GetUsersByApplicationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersByApplicationsOperationCompleted);
            }
            this.InvokeAsync("GetUsersByApplications", new object[] {
                        application}, this.GetUsersByApplicationsOperationCompleted, userState);
        }
        
        private void OnGetUsersByApplicationsOperationCompleted(object arg) {
            if ((this.GetUsersByApplicationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersByApplicationsCompleted(this, new GetUsersByApplicationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CAESDO.Services/GetUsersByApplicationRole", RequestNamespace="CAESDO.Services", ResponseNamespace="CAESDO.Services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CatbertUsers[] GetUsersByApplicationRole(string application, int roleID) {
            object[] results = this.Invoke("GetUsersByApplicationRole", new object[] {
                        application,
                        roleID});
            return ((CatbertUsers[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersByApplicationRoleAsync(string application, int roleID) {
            this.GetUsersByApplicationRoleAsync(application, roleID, null);
        }
        
        /// <remarks/>
        public void GetUsersByApplicationRoleAsync(string application, int roleID, object userState) {
            if ((this.GetUsersByApplicationRoleOperationCompleted == null)) {
                this.GetUsersByApplicationRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersByApplicationRoleOperationCompleted);
            }
            this.InvokeAsync("GetUsersByApplicationRole", new object[] {
                        application,
                        roleID}, this.GetUsersByApplicationRoleOperationCompleted, userState);
        }
        
        private void OnGetUsersByApplicationRoleOperationCompleted(object arg) {
            if ((this.GetUsersByApplicationRoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersByApplicationRoleCompleted(this, new GetUsersByApplicationRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CAESDO.Services/AddEmail", RequestNamespace="CAESDO.Services", ResponseNamespace="CAESDO.Services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddEmail(string login, string emailAddress, int emailTypeID) {
            object[] results = this.Invoke("AddEmail", new object[] {
                        login,
                        emailAddress,
                        emailTypeID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddEmailAsync(string login, string emailAddress, int emailTypeID) {
            this.AddEmailAsync(login, emailAddress, emailTypeID, null);
        }
        
        /// <remarks/>
        public void AddEmailAsync(string login, string emailAddress, int emailTypeID, object userState) {
            if ((this.AddEmailOperationCompleted == null)) {
                this.AddEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddEmailOperationCompleted);
            }
            this.InvokeAsync("AddEmail", new object[] {
                        login,
                        emailAddress,
                        emailTypeID}, this.AddEmailOperationCompleted, userState);
        }
        
        private void OnAddEmailOperationCompleted(object arg) {
            if ((this.AddEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddEmailCompleted(this, new AddEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CAESDO.Services/AddPhoneNumber", RequestNamespace="CAESDO.Services", ResponseNamespace="CAESDO.Services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddPhoneNumber(string login, string phoneNumber, int phoneType) {
            object[] results = this.Invoke("AddPhoneNumber", new object[] {
                        login,
                        phoneNumber,
                        phoneType});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddPhoneNumberAsync(string login, string phoneNumber, int phoneType) {
            this.AddPhoneNumberAsync(login, phoneNumber, phoneType, null);
        }
        
        /// <remarks/>
        public void AddPhoneNumberAsync(string login, string phoneNumber, int phoneType, object userState) {
            if ((this.AddPhoneNumberOperationCompleted == null)) {
                this.AddPhoneNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddPhoneNumberOperationCompleted);
            }
            this.InvokeAsync("AddPhoneNumber", new object[] {
                        login,
                        phoneNumber,
                        phoneType}, this.AddPhoneNumberOperationCompleted, userState);
        }
        
        private void OnAddPhoneNumberOperationCompleted(object arg) {
            if ((this.AddPhoneNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddPhoneNumberCompleted(this, new AddPhoneNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CAESDO.Services/GetEmailTypes", RequestNamespace="CAESDO.Services", ResponseNamespace="CAESDO.Services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmailTypes[] GetEmailTypes() {
            object[] results = this.Invoke("GetEmailTypes", new object[0]);
            return ((EmailTypes[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmailTypesAsync() {
            this.GetEmailTypesAsync(null);
        }
        
        /// <remarks/>
        public void GetEmailTypesAsync(object userState) {
            if ((this.GetEmailTypesOperationCompleted == null)) {
                this.GetEmailTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmailTypesOperationCompleted);
            }
            this.InvokeAsync("GetEmailTypes", new object[0], this.GetEmailTypesOperationCompleted, userState);
        }
        
        private void OnGetEmailTypesOperationCompleted(object arg) {
            if ((this.GetEmailTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmailTypesCompleted(this, new GetEmailTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CAESDO.Services/GetPhoneTypes", RequestNamespace="CAESDO.Services", ResponseNamespace="CAESDO.Services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneTypes[] GetPhoneTypes() {
            object[] results = this.Invoke("GetPhoneTypes", new object[0]);
            return ((PhoneTypes[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPhoneTypesAsync() {
            this.GetPhoneTypesAsync(null);
        }
        
        /// <remarks/>
        public void GetPhoneTypesAsync(object userState) {
            if ((this.GetPhoneTypesOperationCompleted == null)) {
                this.GetPhoneTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPhoneTypesOperationCompleted);
            }
            this.InvokeAsync("GetPhoneTypes", new object[0], this.GetPhoneTypesOperationCompleted, userState);
        }
        
        private void OnGetPhoneTypesOperationCompleted(object arg) {
            if ((this.GetPhoneTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPhoneTypesCompleted(this, new GetPhoneTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1434")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CAESDO.Services")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="CAESDO.Services", IsNullable=false)]
    public partial class SecurityContext : System.Web.Services.Protocols.SoapHeader {
        
        private string userIDField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string userID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1434")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CAESDO.Services")]
    public partial class PhoneTypes {
        
        private int phoneTypeIDField;
        
        private string typeField;
        
        /// <remarks/>
        public int PhoneTypeID {
            get {
                return this.phoneTypeIDField;
            }
            set {
                this.phoneTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1434")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CAESDO.Services")]
    public partial class EmailTypes {
        
        private int emailTypeIDField;
        
        private string typeField;
        
        /// <remarks/>
        public int EmailTypeID {
            get {
                return this.emailTypeIDField;
            }
            set {
                this.emailTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1434")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CAESDO.Services")]
    public partial class Roles {
        
        private int roleIDField;
        
        private string roleField;
        
        /// <remarks/>
        public int RoleID {
            get {
                return this.roleIDField;
            }
            set {
                this.roleIDField = value;
            }
        }
        
        /// <remarks/>
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1434")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CAESDO.Services")]
    public partial class Units {
        
        private int unitIDField;
        
        private string unitField;
        
        /// <remarks/>
        public int UnitID {
            get {
                return this.unitIDField;
            }
            set {
                this.unitIDField = value;
            }
        }
        
        /// <remarks/>
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CatbertUsers))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1434")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CAESDO.Services")]
    public partial class Users {
        
        private string employeeIDField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string loginField;
        
        private string emailField;
        
        private string departmentField;
        
        /// <remarks/>
        public string EmployeeID {
            get {
                return this.employeeIDField;
            }
            set {
                this.employeeIDField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1434")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CAESDO.Services")]
    public partial class CatbertUsers : Users {
        
        private int roleIDField;
        
        private int userIDField;
        
        private string sIDField;
        
        private string roleField;
        
        /// <remarks/>
        public int RoleID {
            get {
                return this.roleIDField;
            }
            set {
                this.roleIDField = value;
            }
        }
        
        /// <remarks/>
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string SID {
            get {
                return this.sIDField;
            }
            set {
                this.sIDField = value;
            }
        }
        
        /// <remarks/>
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void SearchNewUserCompletedEventHandler(object sender, SearchNewUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchNewUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchNewUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Users[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Users[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void InsertNewUserCompletedEventHandler(object sender, InsertNewUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertNewUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertNewUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void VerifyUserCompletedEventHandler(object sender, VerifyUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void AssignPermissionsCompletedEventHandler(object sender, AssignPermissionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AssignPermissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AssignPermissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void DeletePermissionsCompletedEventHandler(object sender, DeletePermissionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeletePermissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeletePermissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void AddUnitCompletedEventHandler(object sender, AddUnitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void DeleteUnitCompletedEventHandler(object sender, DeleteUnitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetUnitsCompletedEventHandler(object sender, GetUnitsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUnitsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUnitsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Units[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Units[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetUnitsByUserCompletedEventHandler(object sender, GetUnitsByUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUnitsByUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUnitsByUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Units[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Units[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetRolesCompletedEventHandler(object sender, GetRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Roles[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Roles[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetRolesByUserCompletedEventHandler(object sender, GetRolesByUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRolesByUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRolesByUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Roles[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Roles[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetUsersByApplicationsCompletedEventHandler(object sender, GetUsersByApplicationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersByApplicationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersByApplicationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CatbertUsers[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CatbertUsers[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetUsersByApplicationRoleCompletedEventHandler(object sender, GetUsersByApplicationRoleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersByApplicationRoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersByApplicationRoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CatbertUsers[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CatbertUsers[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void AddEmailCompletedEventHandler(object sender, AddEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void AddPhoneNumberCompletedEventHandler(object sender, AddPhoneNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddPhoneNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddPhoneNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetEmailTypesCompletedEventHandler(object sender, GetEmailTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmailTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmailTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmailTypes[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmailTypes[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void GetPhoneTypesCompletedEventHandler(object sender, GetPhoneTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPhoneTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPhoneTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneTypes[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneTypes[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591