//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esra.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Esra.Web.Resources.GlobalConstants", typeof(GlobalConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string ROLE_ADMIN {
            get {
                return ResourceManager.GetString("ROLE_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationManager.
        /// </summary>
        public static string ROLE_APPLICATION_MANAGER {
            get {
                return ResourceManager.GetString("ROLE_APPLICATION_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOUser.
        /// </summary>
        public static string ROLE_DO_USER {
            get {
                return ResourceManager.GetString("ROLE_DO_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmulationUser.
        /// </summary>
        public static string ROLE_EMULATION_USER {
            get {
                return ResourceManager.GetString("ROLE_EMULATION_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManageAll.
        /// </summary>
        public static string ROLE_MANAGE_ALL {
            get {
                return ResourceManager.GetString("ROLE_MANAGE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManageSchool.
        /// </summary>
        public static string ROLE_MANAGE_SCHOOL {
            get {
                return ResourceManager.GetString("ROLE_MANAGE_SCHOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer.
        /// </summary>
        public static string ROLE_REVIEWER {
            get {
                return ResourceManager.GetString("ROLE_REVIEWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchoolAdmin.
        /// </summary>
        public static string ROLE_SCHOOL_ADMIN {
            get {
                return ResourceManager.GetString("ROLE_SCHOOL_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string ROLE_USER {
            get {
                return ResourceManager.GetString("ROLE_USER", resourceCulture);
            }
        }
    }
}
