CREATE TABLE [dbo].[CX_20120701] (
    [TITLE_CODE]          NVARCHAR (255) NULL,
    [TITLE_NAME]          NVARCHAR (255) NULL,
    [LOCATION_1]          NVARCHAR (255) NULL,
    [SUB_LOCATION]        NVARCHAR (255) NULL,
    [EFF_BEGIN_DATE]      DATETIME       NULL,
    [PAY_RATE_MONTHLY]    FLOAT (53)     NULL,
    [PAY_RATE_ANNUAL]     FLOAT (53)     NULL,
    [PAY_SCALE_CODE]      NVARCHAR (255) NULL,
    [PAY_RATE_HOURLY_RND] FLOAT (53)     NULL,
    [TITLE_UNIT_CODE]     NVARCHAR (255) NULL,
    [PAY_REP]             NVARCHAR (255) NULL,
    [PAY_INTERVAL]        FLOAT (53)     NULL,
    [STEP_NUMBER]         DECIMAL (4, 1) NULL
);

