CREATE TABLE [dbo].[SalaryData_20140712] (
    [TITLE_CODE]                   NVARCHAR (255)  NULL,
    [TITLE_NAME]                   NVARCHAR (255)  NULL,
    [LOCATION_1]                   NVARCHAR (255)  NULL,
    [SUB_LOCATION]                 NVARCHAR (255)  NULL,
    [SUB_LOCATION_NAME]            NVARCHAR (255)  NULL,
    [TITLE_UNIT_CODE]              NVARCHAR (255)  NULL,
    [TITLE_UNIT_NAME]              NVARCHAR (255)  NULL,
    [LINKAGE_CODE]                 NVARCHAR (255)  NULL,
    [PERSONNEL_PROGRAM]            NVARCHAR (255)  NULL,
    [PAY_REP]                      NVARCHAR (255)  NULL,
    [PAY_INTERVAL]                 DECIMAL (38, 1) NULL,
    [NUMBER_OF_PAY_INTERVALS]      INT             NULL,
    [NUMBER_OF_WHOLE_STEPS]        INT             NULL,
    [MAXSTEP]                      NVARCHAR (255)  NULL,
    [CLASS_TTL_OUTL_CODE]          NVARCHAR (255)  NULL,
    [CLASS_TTL_OUTL_NAME]          NVARCHAR (255)  NULL,
    [LOCATION_1_TITLE]             NVARCHAR (255)  NULL,
    [OVERTIME_EXEMPT_STATUS_CODE]  NVARCHAR (255)  NULL,
    [PERDIEM_FLAG]                 NVARCHAR (255)  NULL,
    [RATE_LOOKUP_FLAG]             NVARCHAR (255)  NULL,
    [RELATED_99_TUC]               NVARCHAR (255)  NULL,
    [SALARY_GRADE_TYPE]            NVARCHAR (255)  NULL,
    [SALARY_GRADE_FLAG]            NVARCHAR (255)  NULL,
    [SALARY_GRADE]                 NVARCHAR (255)  NULL,
    [STANDARD_HOURS]               MONEY           NULL,
    [SUPERVISORY_FLAG]             NVARCHAR (255)  NULL,
    [FROZEN_DATE]                  NVARCHAR (255)  NULL,
    [WILDCARD_FLAG]                NVARCHAR (255)  NULL,
    [BY_AGREEMENT_CODE]            NVARCHAR (255)  NULL,
    [PAY_SCALE_CODE]               NVARCHAR (255)  NULL,
    [STAFF_STEP_SCALE_EXCEPT_FLAG] NVARCHAR (255)  NULL,
    [PAY_RATE_ANNUAL]              MONEY           NULL,
    [PAY_RATE_HOURLY]              MONEY           NULL,
    [PAY_RATE_HOURLY_RND]          MONEY           NULL,
    [PAY_RATE_MONTHLY]             MONEY           NULL,
    [SALARY_RANGE_MAXIMUM]         MONEY           NULL,
    [SALARY_RANGE_MIDPOINT]        MONEY           NULL,
    [SALARY_RANGE_MINIMUM]         MONEY           NULL,
    [SALARY_RANGE_10TH_PCTLE]      MONEY           NULL,
    [SALARY_RANGE_25TH_PCTLE]      MONEY           NULL,
    [SALARY_RANGE_75TH_PCTLE]      MONEY           NULL,
    [SALARY_RANGE_90TH_PCTLE]      MONEY           NULL,
    [EFF_BEGIN_DATE]               DATETIME        NULL,
    [EFF_BEGIN_DATE_OC]            NVARCHAR (255)  NULL,
    [EFF_BEGIN_DATE_SHFT]          NVARCHAR (255)  NULL
);

