CREATE TABLE [dbo].[SRAEmployee] (
    [PkSRAEmployee]            INT             IDENTITY (136, 1) NOT NULL,
    [PkEmployee]               CHAR (13)       NOT NULL,
    [EmployeeID]               CHAR (9)        NOT NULL,
    [TitleCode]                CHAR (4)        NOT NULL,
    [CareerHireDate]           DATETIME        NULL,
    [PPSCareerHireDateChecked] BIT             NULL,
    [ApptHireDate]             DATETIME        NULL,
    [PPSApptHireDateChecked]   BIT             NULL,
    [ExperienceBeginDate]      DATETIME        NULL,
    [DatesHaveBeenAdjusted]    BIT             NULL,
    [DepartmentComments]       VARCHAR (MAX)   NULL,
    [DeansOfficeComments]      VARCHAR (MAX)   NULL,
    [YearsOfService]           DECIMAL (5, 3)  NULL,
    [TimeInTitle]              DECIMAL (5, 3)  NULL,
    [YearsOfExperience]        DECIMAL (5, 3)  NULL,
    [SalaryReviewAnalysisID]   INT             NULL,
    [Created]                  DATETIME        NOT NULL,
    [PayRate]                  DECIMAL (15, 4) NULL,
    [SalaryGrade]              CHAR (1)        NULL,
    [BargainingUnit]           VARCHAR (2)     NULL,
    [SalaryStep]               VARCHAR (4)     NULL,
    [FullName]                 VARCHAR (50)    NULL,
    [AdminDepartmentID]        VARCHAR (6)     NULL,
    [HomeDepartmentID]         VARCHAR (6)     NULL,
    [WorkDepartmentID]         VARCHAR (6)     NULL,
    [Different]                BIT             NOT NULL,
    [FirstName]                VARCHAR (30)    NULL,
    [MiddleName]               VARCHAR (30)    NULL,
    [LastName]                 VARCHAR (30)    NULL,
    [HireDate]                 DATETIME        NULL,
    [BeginDate]                DATETIME        NULL,
    CONSTRAINT [PK_SRAEmployee] PRIMARY KEY CLUSTERED ([PkSRAEmployee] ASC)
);

